/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    roadmaps: Roadmap;
    courses: Course;
    sections: Section;
    lessons: Lesson;
    media: Media;
    'user-progress': UserProgress;
    achievements: Achievement;
    'user-achievements': UserAchievement;
    'points-transactions': PointsTransaction;
    notes: Note;
    comments: Comment;
    notifications: Notification;
    certificates: Certificate;
    streaks: Streak;
    'trainer-topics': TrainerTopic;
    'trainer-tasks': TrainerTask;
    'user-trainer-progress': UserTrainerProgress;
    'faq-items': FaqItem;
    'yandex-disk-imports': YandexDiskImport;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    roadmaps: RoadmapsSelect<false> | RoadmapsSelect<true>;
    courses: CoursesSelect<false> | CoursesSelect<true>;
    sections: SectionsSelect<false> | SectionsSelect<true>;
    lessons: LessonsSelect<false> | LessonsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'user-progress': UserProgressSelect<false> | UserProgressSelect<true>;
    achievements: AchievementsSelect<false> | AchievementsSelect<true>;
    'user-achievements': UserAchievementsSelect<false> | UserAchievementsSelect<true>;
    'points-transactions': PointsTransactionsSelect<false> | PointsTransactionsSelect<true>;
    notes: NotesSelect<false> | NotesSelect<true>;
    comments: CommentsSelect<false> | CommentsSelect<true>;
    notifications: NotificationsSelect<false> | NotificationsSelect<true>;
    certificates: CertificatesSelect<false> | CertificatesSelect<true>;
    streaks: StreaksSelect<false> | StreaksSelect<true>;
    'trainer-topics': TrainerTopicsSelect<false> | TrainerTopicsSelect<true>;
    'trainer-tasks': TrainerTasksSelect<false> | TrainerTasksSelect<true>;
    'user-trainer-progress': UserTrainerProgressSelect<false> | UserTrainerProgressSelect<true>;
    'faq-items': FaqItemsSelect<false> | FaqItemsSelect<true>;
    'yandex-disk-imports': YandexDiskImportsSelect<false> | YandexDiskImportsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  firstName: string;
  lastName: string;
  role: 'admin' | 'student';
  avatar?: (number | null) | Media;
  bio?: string | null;
  totalPoints?: number | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roadmaps".
 */
export interface Roadmap {
  id: number;
  title: string;
  /**
   * Генерируется автоматически из названия
   */
  slug: string;
  description?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  coverImage?: (number | null) | Media;
  order?: number | null;
  isPublished?: boolean | null;
  /**
   * Формат: https://miro.com/app/board/... или https://miro.com/app/embed/... Если указана — отображается на странице роадмапа.
   */
  miroEmbedUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses".
 */
export interface Course {
  id: number;
  title: string;
  /**
   * Генерируется автоматически из названия
   */
  slug: string;
  description?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  coverImage?: (number | null) | Media;
  roadmap: number | Roadmap;
  order?: number | null;
  isPublished?: boolean | null;
  estimatedHours?: number | null;
  /**
   * Курсы, которые нужно завершить перед началом этого курса
   */
  prerequisites?: (number | Course)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sections".
 */
export interface Section {
  id: number;
  title: string;
  /**
   * Генерируется автоматически из названия
   */
  slug: string;
  course: number | Course;
  order?: number | null;
  isPublished?: boolean | null;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lessons".
 */
export interface Lesson {
  id: number;
  title: string;
  /**
   * Генерируется автоматически из названия
   */
  slug: string;
  description?: string | null;
  course: number | Course;
  /**
   * Секция внутри курса. Если не указана — урок отображается без группировки.
   */
  section?: (number | null) | Section;
  order?: number | null;
  isPublished?: boolean | null;
  estimatedMinutes?: number | null;
  content?: (TextBlock | VideoBlock | ImageBlock | LinkBlock | MiroBlock | FileBlock)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TextBlock".
 */
export interface TextBlock {
  content: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'text';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VideoBlock".
 */
export interface VideoBlock {
  title: string;
  videoUrl: string;
  displayMode: 'embed' | 'link';
  description?: string | null;
  durationMinutes?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'video';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageBlock".
 */
export interface ImageBlock {
  image: number | Media;
  caption?: string | null;
  altText?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'image';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LinkBlock".
 */
export interface LinkBlock {
  title: string;
  url: string;
  platform?: ('boosty' | 'telegram' | 'youtube' | 'github' | 'other') | null;
  description?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'link';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MiroBlock".
 */
export interface MiroBlock {
  title: string;
  /**
   * Формат: https://miro.com/app/embed/...
   */
  embedUrl: string;
  height?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'miro';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FileBlock".
 */
export interface FileBlock {
  title: string;
  file: number | Media;
  description?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'file';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-progress".
 */
export interface UserProgress {
  id: number;
  user: number | User;
  lesson: number | Lesson;
  isCompleted?: boolean | null;
  completedAt?: string | null;
  lastAccessedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "achievements".
 */
export interface Achievement {
  id: number;
  title: string;
  description: string;
  icon?: (number | null) | Media;
  pointsReward?: number | null;
  criteriaType: 'lesson_count' | 'course_completion' | 'roadmap_completion' | 'total_points' | 'trainer_task_count';
  /**
   * Для lesson_count: кол-во уроков. Для total_points: кол-во баллов. Для completion: 1.
   */
  criteriaValue: number;
  /**
   * Оставьте пустым для любого курса/роадмапа, или укажите конкретный ID
   */
  criteriaEntityId?: string | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-achievements".
 */
export interface UserAchievement {
  id: number;
  user: number | User;
  achievement: number | Achievement;
  unlockedAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "points-transactions".
 */
export interface PointsTransaction {
  id: number;
  user: number | User;
  amount: number;
  reason:
    | 'lesson_completed'
    | 'course_completed'
    | 'roadmap_completed'
    | 'achievement_unlocked'
    | 'admin_adjustment'
    | 'trainer_task_completed';
  /**
   * ID урока, курса, роадмапа или достижения
   */
  relatedEntity?: string | null;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notes".
 */
export interface Note {
  id: number;
  user: number | User;
  lesson: number | Lesson;
  content: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comments".
 */
export interface Comment {
  id: number;
  user: number | User;
  lesson: number | Lesson;
  content: string;
  /**
   * Оставьте пустым для корневого комментария
   */
  parentComment?: (number | null) | Comment;
  isResolved?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications".
 */
export interface Notification {
  id: number;
  user: number | User;
  title: string;
  message: string;
  type:
    | 'info'
    | 'achievement'
    | 'course_completed'
    | 'roadmap_completed'
    | 'comment'
    | 'trainer_task'
    | 'support_message';
  link?: string | null;
  isRead?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certificates".
 */
export interface Certificate {
  id: number;
  user: number | User;
  type: 'course' | 'roadmap';
  title: string;
  relatedEntity: string;
  issuedAt: string;
  certificateNumber: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "streaks".
 */
export interface Streak {
  id: number;
  user: number | User;
  currentStreak: number;
  longestStreak: number;
  lastActivityDate?: string | null;
  totalActiveDays?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trainer-topics".
 */
export interface TrainerTopic {
  id: number;
  title: string;
  /**
   * Генерируется автоматически из названия
   */
  slug: string;
  description?: string | null;
  /**
   * Emoji или имя иконки lucide (например: "code", "braces", "terminal")
   */
  icon?: string | null;
  order?: number | null;
  isPublished?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trainer-tasks".
 */
export interface TrainerTask {
  id: number;
  title: string;
  /**
   * Генерируется автоматически из названия
   */
  slug: string;
  topic: number | TrainerTopic;
  order?: number | null;
  difficulty: 'easy' | 'medium' | 'hard';
  description: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Шаблон кода, который увидит пользователь. Используйте комментарии для подсказок.
   */
  starterCode: string;
  /**
   * Ожидаемый вывод console.log. Каждая строка — один вызов console.log.
   */
  expectedOutput: string;
  hints?:
    | {
        hint: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Только для администратора. Не показывается пользователям.
   */
  solutionCode?: string | null;
  pointsReward?: number | null;
  isPublished?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-trainer-progress".
 */
export interface UserTrainerProgress {
  id: number;
  user: number | User;
  task: number | TrainerTask;
  isCompleted?: boolean | null;
  userCode?: string | null;
  completedAt?: string | null;
  attempts?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq-items".
 */
export interface FaqItem {
  id: number;
  question: string;
  answer: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  order?: number | null;
  isPublished?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "yandex-disk-imports".
 */
export interface YandexDiskImport {
  id: number;
  publicUrl: string;
  status: 'pending' | 'processing' | 'completed' | 'failed';
  course: number | Course;
  sectionsCreated?: number | null;
  lessonsCreated?: number | null;
  errorLog?: string | null;
  importedBy: number | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'roadmaps';
        value: number | Roadmap;
      } | null)
    | ({
        relationTo: 'courses';
        value: number | Course;
      } | null)
    | ({
        relationTo: 'sections';
        value: number | Section;
      } | null)
    | ({
        relationTo: 'lessons';
        value: number | Lesson;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'user-progress';
        value: number | UserProgress;
      } | null)
    | ({
        relationTo: 'achievements';
        value: number | Achievement;
      } | null)
    | ({
        relationTo: 'user-achievements';
        value: number | UserAchievement;
      } | null)
    | ({
        relationTo: 'points-transactions';
        value: number | PointsTransaction;
      } | null)
    | ({
        relationTo: 'notes';
        value: number | Note;
      } | null)
    | ({
        relationTo: 'comments';
        value: number | Comment;
      } | null)
    | ({
        relationTo: 'notifications';
        value: number | Notification;
      } | null)
    | ({
        relationTo: 'certificates';
        value: number | Certificate;
      } | null)
    | ({
        relationTo: 'streaks';
        value: number | Streak;
      } | null)
    | ({
        relationTo: 'trainer-topics';
        value: number | TrainerTopic;
      } | null)
    | ({
        relationTo: 'trainer-tasks';
        value: number | TrainerTask;
      } | null)
    | ({
        relationTo: 'user-trainer-progress';
        value: number | UserTrainerProgress;
      } | null)
    | ({
        relationTo: 'faq-items';
        value: number | FaqItem;
      } | null)
    | ({
        relationTo: 'yandex-disk-imports';
        value: number | YandexDiskImport;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  role?: T;
  avatar?: T;
  bio?: T;
  totalPoints?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roadmaps_select".
 */
export interface RoadmapsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  coverImage?: T;
  order?: T;
  isPublished?: T;
  miroEmbedUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses_select".
 */
export interface CoursesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  coverImage?: T;
  roadmap?: T;
  order?: T;
  isPublished?: T;
  estimatedHours?: T;
  prerequisites?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sections_select".
 */
export interface SectionsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  course?: T;
  order?: T;
  isPublished?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lessons_select".
 */
export interface LessonsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  course?: T;
  section?: T;
  order?: T;
  isPublished?: T;
  estimatedMinutes?: T;
  content?:
    | T
    | {
        text?: T | TextBlockSelect<T>;
        video?: T | VideoBlockSelect<T>;
        image?: T | ImageBlockSelect<T>;
        link?: T | LinkBlockSelect<T>;
        miro?: T | MiroBlockSelect<T>;
        file?: T | FileBlockSelect<T>;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TextBlock_select".
 */
export interface TextBlockSelect<T extends boolean = true> {
  content?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VideoBlock_select".
 */
export interface VideoBlockSelect<T extends boolean = true> {
  title?: T;
  videoUrl?: T;
  displayMode?: T;
  description?: T;
  durationMinutes?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageBlock_select".
 */
export interface ImageBlockSelect<T extends boolean = true> {
  image?: T;
  caption?: T;
  altText?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LinkBlock_select".
 */
export interface LinkBlockSelect<T extends boolean = true> {
  title?: T;
  url?: T;
  platform?: T;
  description?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MiroBlock_select".
 */
export interface MiroBlockSelect<T extends boolean = true> {
  title?: T;
  embedUrl?: T;
  height?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FileBlock_select".
 */
export interface FileBlockSelect<T extends boolean = true> {
  title?: T;
  file?: T;
  description?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-progress_select".
 */
export interface UserProgressSelect<T extends boolean = true> {
  user?: T;
  lesson?: T;
  isCompleted?: T;
  completedAt?: T;
  lastAccessedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "achievements_select".
 */
export interface AchievementsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  icon?: T;
  pointsReward?: T;
  criteriaType?: T;
  criteriaValue?: T;
  criteriaEntityId?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-achievements_select".
 */
export interface UserAchievementsSelect<T extends boolean = true> {
  user?: T;
  achievement?: T;
  unlockedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "points-transactions_select".
 */
export interface PointsTransactionsSelect<T extends boolean = true> {
  user?: T;
  amount?: T;
  reason?: T;
  relatedEntity?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notes_select".
 */
export interface NotesSelect<T extends boolean = true> {
  user?: T;
  lesson?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comments_select".
 */
export interface CommentsSelect<T extends boolean = true> {
  user?: T;
  lesson?: T;
  content?: T;
  parentComment?: T;
  isResolved?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications_select".
 */
export interface NotificationsSelect<T extends boolean = true> {
  user?: T;
  title?: T;
  message?: T;
  type?: T;
  link?: T;
  isRead?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certificates_select".
 */
export interface CertificatesSelect<T extends boolean = true> {
  user?: T;
  type?: T;
  title?: T;
  relatedEntity?: T;
  issuedAt?: T;
  certificateNumber?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "streaks_select".
 */
export interface StreaksSelect<T extends boolean = true> {
  user?: T;
  currentStreak?: T;
  longestStreak?: T;
  lastActivityDate?: T;
  totalActiveDays?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trainer-topics_select".
 */
export interface TrainerTopicsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  icon?: T;
  order?: T;
  isPublished?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trainer-tasks_select".
 */
export interface TrainerTasksSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  topic?: T;
  order?: T;
  difficulty?: T;
  description?: T;
  starterCode?: T;
  expectedOutput?: T;
  hints?:
    | T
    | {
        hint?: T;
        id?: T;
      };
  solutionCode?: T;
  pointsReward?: T;
  isPublished?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-trainer-progress_select".
 */
export interface UserTrainerProgressSelect<T extends boolean = true> {
  user?: T;
  task?: T;
  isCompleted?: T;
  userCode?: T;
  completedAt?: T;
  attempts?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq-items_select".
 */
export interface FaqItemsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  order?: T;
  isPublished?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "yandex-disk-imports_select".
 */
export interface YandexDiskImportsSelect<T extends boolean = true> {
  publicUrl?: T;
  status?: T;
  course?: T;
  sectionsCreated?: T;
  lessonsCreated?: T;
  errorLog?: T;
  importedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  platformName: string;
  platformDescription?: string | null;
  logo?: (number | null) | Media;
  points: {
    lessonCompleted: number;
    courseCompleted: number;
    roadmapCompleted: number;
    trainerTaskCompleted: number;
  };
  contacts?: {
    /**
     * Ссылка на Telegram-канал (например: https://t.me/your_channel)
     */
    telegramChannel?: string | null;
    /**
     * Ссылка на Telegram-группу для учеников
     */
    telegramGroup?: string | null;
    website?: string | null;
    email?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  platformName?: T;
  platformDescription?: T;
  logo?: T;
  points?:
    | T
    | {
        lessonCompleted?: T;
        courseCompleted?: T;
        roadmapCompleted?: T;
        trainerTaskCompleted?: T;
      };
  contacts?:
    | T
    | {
        telegramChannel?: T;
        telegramGroup?: T;
        website?: T;
        email?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}